# Generated by Django 4.0.1 on 2022-01-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=100)),
            ],
        ),
    ]
